// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "b8d67c20-938b-400c-9f92-ed535b5916b3");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1675374878);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1675374859);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1675374855);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8bcb3026-621f-44d6-bdda-83252e8597ae}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1675374848);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1aa099db-8775-438c-a02f-ca4e2eeeebf3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1675374850);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1675374864174");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1675396464174");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1675374855");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20221215175817");
user_pref("browser.startup.homepage_override.mstone", "108.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1675374851);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1675374854398");
user_pref("distribution.iniFile.exists.appversion", "108.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint-001.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "3a59a019ccea476cb2c0082f44253893");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1675374849);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-CA@firefox.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20221215175817");
user_pref("extensions.lastAppVersion", "108.0.1");
user_pref("extensions.lastPlatformVersion", "108.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"fd1b5ecb-3495-4042-ad85-4a6d3cfd4c55\",\"pictureinpicture@mozilla.org\":\"db0a8a10-825c-445d-b66c-fefc1c37dd84\",\"screenshots@mozilla.org\":\"df5ca106-b991-4235-bd36-b94f5fdad9f8\",\"webcompat-reporter@mozilla.org\":\"9656af7f-49bc-4e5e-bf5f-0882672020d1\",\"webcompat@mozilla.org\":\"0288cacb-55a7-47cb-b79d-a3a08729e492\",\"default-theme@mozilla.org\":\"d7649ab7-e2fc-4412-8f17-65219308a3b7\",\"addons-search-detection@mozilla.com\":\"e7dc985a-7cb0-4ed5-9d24-468400257f59\",\"google@search.mozilla.org\":\"b1b09d2f-d465-480a-a590-886c7ad4e0d2\",\"amazondotcom@search.mozilla.org\":\"3ef52b62-b040-4aee-991a-b2d59717ddcf\",\"wikipedia@search.mozilla.org\":\"fb50cc05-d617-44ba-baae-9404f7aad325\",\"bing@search.mozilla.org\":\"3da6061c-fbcb-4f14-bc98-7bf450841203\",\"ddg@search.mozilla.org\":\"66695364-9d0e-421e-9f93-89c433102c98\",\"ebay@search.mozilla.org\":\"5133eb55-c2bc-4ff1-b48d-8c758ad0a235\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1675374858);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "24bd8f40-8a6c-46b0-ba83-c14c060e9786");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1675374845);
user_pref("toolkit.telemetry.cachedClientID", "faade42a-7184-4511-8737-252fef5cfe9c");
user_pref("toolkit.telemetry.previousBuildID", "20221215175817");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
